title: Gautam Ojha # your name (or website title) here
logo: "/images/logo.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MS CS Student at University of Illinois at Chicago
  <br><br>
  Developing Software Applications using Java, Scala, Spring Boot.
  <br><br>
  <a href="https://www.linkedin.com/in/gautamojha/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
